// Code generated by MockGen. DO NOT EDIT.
// Source: ./store/feira/feira.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/unico/FeirasLivresAPI/model"
)

// MockFeiraStore is a mock of Store interface.
type MockFeiraStore struct {
	ctrl     *gomock.Controller
	recorder *MockFeiraStoreMockRecorder
}

// MockFeiraStoreMockRecorder is the mock recorder for MockFeiraStore.
type MockFeiraStoreMockRecorder struct {
	mock *MockFeiraStore
}

// NewMockFeiraStore creates a new mock instance.
func NewMockFeiraStore(ctrl *gomock.Controller) *MockFeiraStore {
	mock := &MockFeiraStore{ctrl: ctrl}
	mock.recorder = &MockFeiraStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeiraStore) EXPECT() *MockFeiraStoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockFeiraStore) Create(ctx context.Context, feira model.FeiraRequest) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, feira)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockFeiraStoreMockRecorder) Create(ctx, feira interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFeiraStore)(nil).Create), ctx, feira)
}

// Delete mocks base method.
func (m *MockFeiraStore) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockFeiraStoreMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockFeiraStore)(nil).Delete), ctx, id)
}

// ReadOne mocks base method.
func (m *MockFeiraStore) ReadOne(ctx context.Context, id string) (*model.Feira, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadOne", ctx, id)
	ret0, _ := ret[0].(*model.Feira)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadOne indicates an expected call of ReadOne.
func (mr *MockFeiraStoreMockRecorder) ReadOne(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadOne", reflect.TypeOf((*MockFeiraStore)(nil).ReadOne), ctx, id)
}

// Search mocks base method.
func (m *MockFeiraStore) Search(ctx context.Context, distrito string) ([]*model.Feira, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, distrito)
	ret0, _ := ret[0].([]*model.Feira)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockFeiraStoreMockRecorder) Search(ctx, distrito interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockFeiraStore)(nil).Search), ctx, distrito)
}

// Update mocks base method.
func (m *MockFeiraStore) Update(ctx context.Context, id string, feira model.FeiraRequest) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, feira)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockFeiraStoreMockRecorder) Update(ctx, id, feira interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockFeiraStore)(nil).Update), ctx, id, feira)
}
